[editor]
line-number = "relative"
mouse = true
cursorline = true
color-modes = true
rulers = [80, 120]
scroll-lines = 3
bufferline = "multiple"

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = ["mode", "file-name", "file-type", "version-control"]
center= ["spinner", "diagnostics"]
right= ["selections", "position", "position-percentage"]

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"

[keys.normal]
C-q = ":q"

C-v = "vsplit"
C-x = "hsplit"

x = "extend_line_below"
X = "extend_line_above"

C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"

# Use one escape key for all uses
# https://www.youtube.com/watch?v=aiSI6vdZWgE
esc = ["collapse_selection", "keep_primary_selection"]
