[editor]
line-number = "relative"
mouse = false
cursorline = true
color-modes = true
rulers = [80, 120]

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true

[editor.statusline]
left = ["mode", "file-name", "file-type"]
center = ["selections", "position", "position-percentage"]
right = ["spinner", "diagnostics"]

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"

[keys.normal]
C-q = ":q"

C-v = "vsplit"
C-x = "hsplit"

C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
