[[language]]
name = "lua"
language-server = { command = "/Users/jesse/.local/share/nvim/lsp_servers/sumneko_lua/extension/server/bin/lua-language-server" }

[[language]]
name = "elixir"
language-server = { command = "/Users/jesse/.local/share/nvim/lsp_servers/elixirls/elixir-ls/language_server.sh" }

[[language]]
name = "python"
language-server = { command = "/Users/jesse/.local/share/nvim/lsp_servers/pylsp/venv/bin/pylsp" }

[[language]]
name = "javascript"
language-server = { command = "/Users/jesse/.local/share/nvim/lsp_servers/tsserver/node_modules/.bin/typescript-language-server", args = ["--stdio"], language-id = "javascript" }

[[language]]
name = "typescript"
language-server = { command = "/Users/jesse/.local/share/nvim/lsp_servers/tsserver/node_modules/.bin/typescript-language-server", args = ["--stdio"], language-id = "typescript" }

[[language]]
name = "bash"
language-server = { command = "/Users/jesse/.local/share/nvim/lsp_servers/bashls/node_modules/.bin/bash-language-server", args = ["start"] }
