work-duration = 1500
short-break-duration = 300
long-break-duration = 900

timer-started-hook = "terminal-notifier -group 'comodoro-notify' -message 'Timer started'"
timer-stopped-hook = "terminal-notifier -group 'comodoro-notify' -message 'Timer stopped'"

[tcp]
host = "localhost"
port = 9090
