[tools]
nim = 'latest'
python = 'latest'
clojure = 'latest'
erlang = 'ref:OTP-25.3.2.2'
elixir = 'ref:v1.14.5'
golang = 'latest'
zig = 'latest'
rust = 'latest'
racket = 'latest'
nodejs = 'latest'
lua = 'latest'
ocaml = 'latest'
ruby = 'latest'
haskell = '9.0.1'
php = '8.2.7'
