[pomodoro]
preset = "pomodoro"

tcp-host = "localhost"
tcp-port = 9999

on-server-start  = "terminal-notifier -sound default -group 'comodoro-notify' -message 'Server started'"
on-server-stopping = "terminal-notifier -sound default -group 'comodoro-notify' -message 'Server stopping'"
on-server-stop  = "terminal-notifier -sound default -group 'comodoro-notify' -message 'Server stopped'"

on-timer-start = "terminal-notifier -sound default -group 'comodoro-notify' -message 'Timer started'"
on-timer-stop = "terminal-notifier -sound default -group 'comodoro-notify' -message 'Timer stopped'; comodoro stop pomodoro tcp"

on-work-pause = "terminal-notifier -sound default -group 'comodoro-notify' -message 'Timer paused'"
