-- Safely try and require impatient.nvim
pcall(require, "impatient")

require("user.options")
require("user.options.abbrs")
require("user.plugins")
require("user.plugins.fine-cmdline-nvim")
require("user.ui")
require("user.keymaps")
require("user.spotlight")
require("user.vcs")
require("user.buffers")
require("user.lsp")
require("user.undo")
require("user.languages.rust")
require("user.languages.python2")
require("user.languages.python3")
require("user.file_system")
require("user.completion")
require("user.search")
require("user.terminal")
