[[language]]
name = "elixir"
language-servers = ["nextls", "elixir-ls"]

[language-server.nextls]
command = "nextls"
args = ["--stdio=true", "--port=9011"]

[language-server.elixir-ls]
command = "elixir-ls"
config = { elixirLS.dialyzerEnabled = true }

[[language]]
name = "python"
language-servers = [ "basedpyright" ]
