matches:
  - trigger: ":jc"
    replace: "jesse.claven@me.com"

  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  - trigger: ":time"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%H:%M"
